In [1]:
# Setup: run this cell, then build the analysis below it.
from pathlib import Path
from urllib.request import urlopen
import json

import pandas as pd
import numpy as np

RELATIVE_DATA_PATH = Path("data/week02_python_objects_posts.json")
RAW_DATA_URL = (
    "https://raw.githubusercontent.com/macss-berkeley/compss-211a/"
    "main/data/week02_python_objects_posts.json"
)

def find_local_file(relative_path):
    for base in (Path.cwd(), *Path.cwd().parents):
        candidate = base / relative_path
        if candidate.exists():
            return candidate
    return None

local_data = find_local_file(RELATIVE_DATA_PATH)
if local_data is not None:
    data_source = str(local_data)
    records = json.loads(local_data.read_text(encoding="utf-8"))
else:
    data_source = RAW_DATA_URL
    with urlopen(RAW_DATA_URL, timeout=30) as response:
        records = json.load(response)

posts = pd.DataFrame(records)
display(posts.head())
print(f"Loaded {len(posts)} rows from {data_source}")

,post_id,author,platform,text,likes,verified,region,year,publication_status
0,1,user_101,forum,Public transit should be free.,27.0,False,West,2024,published
1,2,user_102,forum,The city needs more protected bike lanes.,42.0,True,West,2024,published
2,3,user_103,microblog,None,5.0,False,South,2025,published
3,4,user_104,microblog,Remote work has changed downtown neighborhoods.,31.0,True,Northeast,2025,published
4,5,user_105,forum,Libraries are essential public infrastructure.,18.0,False,South,2025,published

Loaded 90 rows from /Users/jeannettejasmine/Desktop/Computing I/compss-211a/data/week02_python_objects_posts.json

### Your manager's request

"We can focus our next transit outreach pilot on **one platform**. Which should we prioritize, and why?"

Work with the same partner throughout. Use the **text to identify relevant posts**, then compare their **likes** across platforms.

Test whether a minimum-like rule helps remove irrelevant material, and inspect which useful posts it would exclude. Likes are a screening signal to investigate; read the text to judge relevance.

By the end of class, produce **one summary table or chart and a recommendation**. Explain your time period, any like cutoff, what counted as relevant, and one uncertainty that could change your advice.

### Duo task 1 · Decide which posts to include (5-10min)

Choose **both years** or **2025 only**, the latest year in the data. Explain what your choice gains and leaves out.

Inspect some posts with low like counts. Would a minimum-like rule help remove irrelevant material? **Try different thresholds**, such as 10 and 20 likes. For each, identify an irrelevant post it excludes and a relevant post it excludes. Use the text to judge relevance.

Choose a like cutoff, or keep posts regardless of likes. Apply your period and like-count rules to `published_posts` and save the result as `analysis_posts`. Keep all columns, use `.copy()`, and apply the same rules to both platforms. Keep `published_posts` available to inspect exclusions later.

*Hint: combine conditions using `&`, with parentheses around each condition.*

Check what happens at exactly your threshold and when the like count is missing.

**Discuss:** What irrelevant material does your rule remove? What useful transit discussion does it lose? Does that tradeoff help answer the manager's question?

In [19]:
posts[posts["year"] >= 2023]

,post_id,author,platform,text,likes,verified,region,year,publication_status
0,1,user_101,forum,Public transit should be free.,27.0,False,West,2024,published
1,2,user_102,forum,The city needs more protected bike lanes.,42.0,True,West,2024,published
2,3,user_103,forum,None,5.0,False,South,2025,published
3,4,user_104,forum,Remote work has changed downtown neighborhoods.,31.0,True,Northeast,2025,published
4,5,user_105,forum,Libraries are essential public infrastructure.,18.0,False,South,2025,published
...,...,...,...,...,...,...,...,...,...
85,86,user_104,forum,Transit should run later on Sundays.,8.0,True,Northeast,2024,published
86,87,user_106,forum,More buses would make the school run easier.,10.0,False,West,2024,published
87,88,user_117,forum,Bike parking is full outside the library.,11.0,False,Northeast,2024,published
88,89,user_118,forum,The subway timetable needs to be easier to read.,6.0,True,West,2024,published
89,90,user_103,forum,Public transport should connect the clinic to ...,12.0,False,South,2024,published

### Duo task 2 · Decide what counts as relevant (5-10min)

Choose a keyword rule for transit outreach. Should it cover bus services, bike lanes, or commuting?

Write `classify_topic(text)`, using the demo as a starting point. Return `match` when your rule matches, `no_match` when it does not, and `unknown` when text is missing or blank.

Test a clear match, a non-match, a borderline example, and absent text. Apply the function to create `analysis_posts["topic_status"]`. 

Create a new DF `topic_posts` that holds all the relevant posts.

**Discuss:** Which relevant posts might your rule miss, and which might it include by mistake? Revisit your excluded examples in `published_posts`: did the like cutoff remove useful discussion under your topic definition?

### Duo task 3 · Give the manager advice (5-10min)

Use `groupby` on `topic_posts` to compare platforms. Show the **number of matching posts and known like counts** beside the result.

Choose **mean or median likes** to guide your recommendation. Explain what that measure tells the manager.

Check how one alternative changes the recommendation: your other like cutoff, the period, topic rule, or summary measure. Change one choice at a time. If you change the period or cutoff, rebuild `analysis_posts` from `published_posts`. After changing an inclusion or topic rule, rerun `.apply()`, rebuild `topic_posts`, and recalculate.

Finish with one table or chart labeled with your **period, like-count rule, and topic rule**. Recommend a platform and explain one uncertainty. Use an actual excluded post to explain what your selection leaves out; account for missing text or likes separately.